### ISSUE TITLE
Cannot add calendar: Time Ruler: Error creating calendar – Cannot add property 0, object is not extensible

### ISSUE THREAD

**Issue by jnnkB** [j-palindrome/obsidian-time-ruler#109]
**Describe the bug**
Adding an iCal calendar does not work.

**To Reproduce**
1. Go to settings and add a link towards an iCal calendar
2. You get the message "Time Ruler: Error creating calendar – Cannot add property 0, object is not extensible"

As a first attempt of narrowing down the issue, I created an own ICS file that I uploaded to my server. Unfortunately, the error remains when using that file. You can download it here: [demo.txt](https://github.com/joshuatazrein/obsidian-time-ruler/files/14887976/demo.txt).

**Expected behavior**
The calendar should be added.

**Obsidian Version:** 
Tested on desktop version only.

If there is any further information, I am happy to provide that.

**Comment by joshuatazrein** [comment]
Thanks I'll take a look! Probably a readonly object that needs to be copied.

**Comment by eden-chan** [comment]
<img width="900" alt="image" src="https://github.com/j-palindrome/obsidian-time-ruler/assets/60107091/86c7dae7-251c-4d1e-9c5b-a4ad03cfeead">
Getting the same issue when I get my Google Calendar shareable ICS format link: 
<img width="615" alt="image" src="https://github.com/j-palindrome/obsidian-time-ruler/assets/60107091/bf70a3a2-da00-418c-9ec0-ad314357979c">

**Comment by j-palindrome** [comment]
As far as I know this is fixed.

**Comment by jonaskindler93** [comment]
I still get this same error when trying to add google calendars?

**Comment by jenpritchard** [comment]
I'm getting the same exact error

**Comment by j-palindrome** [comment]
Huh...yeah this seems like one of those obscure low-level incompatibility bugs. Glad it's fixed!
