### ISSUE TITLE
Days to due date are displayed with decimal places 

### ISSUE THREAD

**Issue by floroh** [j-palindrome/obsidian-time-ruler#133]
**Describe the bug**
The number of days to the due date of a task is displayed with decimal places, when >19, at least in this example.

**To Reproduce**
1. Setup new vault in Obsidian 1.6.7
2. Install newest versions of community plugins: Time Ruler 2.5.1, Tasks 7.11.0, Dataview 0.5.67
3. Create some tasks with due dates, see attached screenshot
 
**Expected behavior**
The days should be displayed "20d", "21d" etc.

**Screenshots**
![time-ruler-bug](https://github.com/user-attachments/assets/a2a0cb20-1882-4ae7-b829-c5cb8498a6cb)

**Obsidian Version:** 
- [x] Mobile
- [x] Desktop

**Comment by j-palindrome** [comment]
Fixed in 2.5.2!

**Comment by floroh** [comment]
Unfortunately, I still have this issue after updating (and restarting Obisidian) :|
![grafik](https://github.com/user-attachments/assets/72e4e13c-65e6-4eb1-9d5b-264fc89662bd)
